use_frameworks!

target 'react-native-xsy-upgrade_Example' do
  pod ‘RNXSYUpgrade’, :path => '../'

  target 'react-native-xsy-upgrade_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
